# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/Section_debug.bd
# Block Designs: The module: 'Section_debug' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_zynq_ultra_ps_e_1_0/Section_debug_zynq_ultra_ps_e_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_zynq_ultra_ps_e_1_0 || ORIG_REF_NAME==Section_debug_zynq_ultra_ps_e_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_proc_sys_reset_0_0/Section_debug_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_proc_sys_reset_0_0 || ORIG_REF_NAME==Section_debug_proc_sys_reset_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_xlconstant_0_0/Section_debug_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_xlconstant_0_0 || ORIG_REF_NAME==Section_debug_xlconstant_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_pc_unit_0_0/Section_debug_pc_unit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_pc_unit_0_0 || ORIG_REF_NAME==Section_debug_pc_unit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_xlconstant_0_1/Section_debug_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_xlconstant_0_1 || ORIG_REF_NAME==Section_debug_xlconstant_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_xlconstant_3_0/Section_debug_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_xlconstant_3_0 || ORIG_REF_NAME==Section_debug_xlconstant_3_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_ila_0_0/Section_debug_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_ila_0_0 || ORIG_REF_NAME==Section_debug_ila_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_vio_0_0/Section_debug_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_vio_0_0 || ORIG_REF_NAME==Section_debug_vio_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_util_vector_logic_0_0/Section_debug_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_util_vector_logic_0_0 || ORIG_REF_NAME==Section_debug_util_vector_logic_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_pc_to_rom_addr_0_1/Section_debug_pc_to_rom_addr_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_pc_to_rom_addr_0_1 || ORIG_REF_NAME==Section_debug_pc_to_rom_addr_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_blk_mem_gen_0_1/Section_debug_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_blk_mem_gen_0_1 || ORIG_REF_NAME==Section_debug_blk_mem_gen_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_xlconstant_1_0/Section_debug_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_xlconstant_1_0 || ORIG_REF_NAME==Section_debug_xlconstant_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_rv32i_decoder_0_0/Section_debug_rv32i_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_rv32i_decoder_0_0 || ORIG_REF_NAME==Section_debug_rv32i_decoder_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_ila_0_1/Section_debug_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_ila_0_1 || ORIG_REF_NAME==Section_debug_ila_0_1} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_zynq_ultra_ps_e_1_0/Section_debug_zynq_ultra_ps_e_1_0_ooc.xdc

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_zynq_ultra_ps_e_1_0/Section_debug_zynq_ultra_ps_e_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Section_debug_zynq_ultra_ps_e_1_0 || ORIG_REF_NAME==Section_debug_zynq_ultra_ps_e_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_proc_sys_reset_0_0/Section_debug_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Section_debug_proc_sys_reset_0_0 || ORIG_REF_NAME==Section_debug_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_proc_sys_reset_0_0/Section_debug_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Section_debug_proc_sys_reset_0_0 || ORIG_REF_NAME==Section_debug_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Section_debug_ila_0_0 || ORIG_REF_NAME==Section_debug_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Section_debug_ila_0_0 || ORIG_REF_NAME==Section_debug_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_ila_0_0/Section_debug_ila_0_0_ooc.xdc

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_vio_0_0/Section_debug_vio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_vio_0_0 || ORIG_REF_NAME==Section_debug_vio_0_0} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_blk_mem_gen_0_1/Section_debug_blk_mem_gen_0_1_ooc.xdc

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Section_debug_ila_0_1 || ORIG_REF_NAME==Section_debug_ila_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_ila_0_1/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Section_debug_ila_0_1 || ORIG_REF_NAME==Section_debug_ila_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_ila_0_1/Section_debug_ila_0_1_ooc.xdc

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/Section_debug_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Section_debug'. Do not add the DONT_TOUCH constraint.

# Block Designs: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/Section_debug.bd
# Block Designs: The module: 'Section_debug' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_zynq_ultra_ps_e_1_0/Section_debug_zynq_ultra_ps_e_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_zynq_ultra_ps_e_1_0 || ORIG_REF_NAME==Section_debug_zynq_ultra_ps_e_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_proc_sys_reset_0_0/Section_debug_proc_sys_reset_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_proc_sys_reset_0_0 || ORIG_REF_NAME==Section_debug_proc_sys_reset_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_xlconstant_0_0/Section_debug_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_xlconstant_0_0 || ORIG_REF_NAME==Section_debug_xlconstant_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_pc_unit_0_0/Section_debug_pc_unit_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_pc_unit_0_0 || ORIG_REF_NAME==Section_debug_pc_unit_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_xlconstant_0_1/Section_debug_xlconstant_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_xlconstant_0_1 || ORIG_REF_NAME==Section_debug_xlconstant_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_xlconstant_3_0/Section_debug_xlconstant_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_xlconstant_3_0 || ORIG_REF_NAME==Section_debug_xlconstant_3_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_ila_0_0/Section_debug_ila_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_ila_0_0 || ORIG_REF_NAME==Section_debug_ila_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_vio_0_0/Section_debug_vio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_vio_0_0 || ORIG_REF_NAME==Section_debug_vio_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_util_vector_logic_0_0/Section_debug_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_util_vector_logic_0_0 || ORIG_REF_NAME==Section_debug_util_vector_logic_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_pc_to_rom_addr_0_1/Section_debug_pc_to_rom_addr_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_pc_to_rom_addr_0_1 || ORIG_REF_NAME==Section_debug_pc_to_rom_addr_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_blk_mem_gen_0_1/Section_debug_blk_mem_gen_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_blk_mem_gen_0_1 || ORIG_REF_NAME==Section_debug_blk_mem_gen_0_1} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_xlconstant_1_0/Section_debug_xlconstant_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_xlconstant_1_0 || ORIG_REF_NAME==Section_debug_xlconstant_1_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_rv32i_decoder_0_0/Section_debug_rv32i_decoder_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_rv32i_decoder_0_0 || ORIG_REF_NAME==Section_debug_rv32i_decoder_0_0} -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_ila_0_1/Section_debug_ila_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_ila_0_1 || ORIG_REF_NAME==Section_debug_ila_0_1} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_zynq_ultra_ps_e_1_0/Section_debug_zynq_ultra_ps_e_1_0_ooc.xdc

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_zynq_ultra_ps_e_1_0/Section_debug_zynq_ultra_ps_e_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Section_debug_zynq_ultra_ps_e_1_0 || ORIG_REF_NAME==Section_debug_zynq_ultra_ps_e_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_proc_sys_reset_0_0/Section_debug_proc_sys_reset_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Section_debug_proc_sys_reset_0_0 || ORIG_REF_NAME==Section_debug_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_proc_sys_reset_0_0/Section_debug_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Section_debug_proc_sys_reset_0_0 || ORIG_REF_NAME==Section_debug_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Section_debug_ila_0_0 || ORIG_REF_NAME==Section_debug_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Section_debug_ila_0_0 || ORIG_REF_NAME==Section_debug_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_ila_0_0/Section_debug_ila_0_0_ooc.xdc

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_vio_0_0/Section_debug_vio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Section_debug_vio_0_0 || ORIG_REF_NAME==Section_debug_vio_0_0} -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_blk_mem_gen_0_1/Section_debug_blk_mem_gen_0_1_ooc.xdc

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Section_debug_ila_0_1 || ORIG_REF_NAME==Section_debug_ila_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_ila_0_1/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Section_debug_ila_0_1 || ORIG_REF_NAME==Section_debug_ila_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/ip/Section_debug_ila_0_1/Section_debug_ila_0_1_ooc.xdc

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR_Firmware/CPU_N1_ONECYCLE_RISCV_2020_1_MYIR_BRAM_DP/CPU_V1/CPU_V1.srcs/sources_1/bd/Section_debug/Section_debug_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Section_debug'. Do not add the DONT_TOUCH constraint.
