# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR-Firmware/CPU_N1_ONE_CYCLE_FULL_RISCV_REAL/CPU_V1/CPU_V1.srcs/sources_1/bd/RISCV/ip/RISCV_processing_system7_0_0/RISCV_processing_system7_0_0.xci
# IP: The module: 'RISCV_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR-Firmware/CPU_N1_ONE_CYCLE_FULL_RISCV_REAL/CPU_V1/CPU_V1.srcs/sources_1/bd/RISCV/ip/RISCV_processing_system7_0_0/RISCV_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'RISCV_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR-Firmware/CPU_N1_ONE_CYCLE_FULL_RISCV_REAL/CPU_V1/CPU_V1.srcs/sources_1/bd/RISCV/ip/RISCV_processing_system7_0_0/RISCV_processing_system7_0_0.xci
# IP: The module: 'RISCV_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/steckler/xilinx_linux/SDR_custom/SDR/Software/SDR-Firmware/CPU_N1_ONE_CYCLE_FULL_RISCV_REAL/CPU_V1/CPU_V1.srcs/sources_1/bd/RISCV/ip/RISCV_processing_system7_0_0/RISCV_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'RISCV_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
