#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Dec 13 20:45:17 WET 2025
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_cpu_behav -key {Behavioral:sim_1:Functional:tb_cpu} -tclbatch tb_cpu.tcl -protoinst "protoinst_files/A.protoinst" -view /media/steckler/xilinx_linux/SDR_custom/SDR/Software/CPU_N1/CPU_V1/simulation/tb_cpu_behav_iROM.wcfg -log simulate.log"
xsim tb_cpu_behav -key {Behavioral:sim_1:Functional:tb_cpu} -tclbatch tb_cpu.tcl -protoinst "protoinst_files/A.protoinst" -view /media/steckler/xilinx_linux/SDR_custom/SDR/Software/CPU_N1/CPU_V1/simulation/tb_cpu_behav_iROM.wcfg -log simulate.log

