# ============================================================
# Pluto project - user controlled BD (FINAL – NO WRAPPER)
# Vivado 2019.1 / ADI HDL / Batch-safe
# ============================================================

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------
set script_dir [file dirname [info script]]
set ad_hdl_dir [file normalize "$script_dir/../../../plutosdr-fw/hdl"]

# ------------------------------------------------------------
# ADI environment
# ------------------------------------------------------------
source "$ad_hdl_dir/projects/scripts/adi_env.tcl"
source "$ad_hdl_dir/projects/scripts/adi_project_xilinx.tcl"
source "$ad_hdl_dir/projects/scripts/adi_board.tcl"

# ------------------------------------------------------------
# Tell ADI to use USER Block Design
# ------------------------------------------------------------
# Source of truth: fpga/pluto/bd/system_bd.tcl
set ::ADI_PROJECT_BD_TCL "$script_dir/../bd/system_bd.tcl"
file copy -force "$::ADI_PROJECT_BD_TCL" "system_bd.tcl"

# ------------------------------------------------------------
# CRITICAL: disable ADI auto-generated system_wrapper
# ------------------------------------------------------------
# This prevents ADI from generating system_wrapper.tcl and
# forcing system_wrapper as TOP during impl_1 (in patched ADI HDL)
set ::ADI_NO_PROJECT_WRAPPER 1

# ------------------------------------------------------------
# Create project
# ------------------------------------------------------------
set p_device "xc7z010clg225-1"
adi_project pluto

# ------------------------------------------------------------
# Generate BD outputs explicitly
# ------------------------------------------------------------
# Ensures system.v exists and is treated as normal RTL
generate_target all [get_files system.bd]

# ------------------------------------------------------------
# Add BD HDL (NO wrapper)
# ------------------------------------------------------------
set bd_gen_dir "./pluto.srcs/sources_1/bd/system"

add_files -fileset sources_1 -norecurse \
  $bd_gen_dir/synth/system.v

update_compile_order -fileset sources_1

# ------------------------------------------------------------
# FORCE TOP = system (CRITICAL)
# ------------------------------------------------------------
set_property top system [current_fileset]

# ------------------------------------------------------------
# Extra project files (minimal)
# ------------------------------------------------------------
adi_project_files pluto [list \
  "$ad_hdl_dir/library/common/ad_iobuf.v" \
]

# ------------------------------------------------------------
# Disable autogenerated PS7 XDC (if present)
# ------------------------------------------------------------
set ps7_xdc [get_files -quiet *system_sys_ps7_0.xdc]
if {[llength $ps7_xdc] > 0} {
  set_property is_enabled false $ps7_xdc
}

# ------------------------------------------------------------
# Run synthesis + implementation
# ------------------------------------------------------------
launch_runs synth_1
wait_on_run synth_1

launch_runs impl_1
wait_on_run impl_1

# ------------------------------------------------------------
# Apply AD9361 timing (OPTIONAL; design must be open)
# ------------------------------------------------------------
# Note: axi_ad9361_delay.tcl may fail if expected ports/pins do not exist
# in this project variant. We make it non-fatal.
open_run impl_1 -name impl_1

# Check if the objects that the script expects actually exist
set rx_ports  [get_ports -quiet -filter {NAME =~ rx_*_in*}]
set iddr_pins [get_pins  -quiet -hierarchical -filter {NAME =~ *i_rx_data_iddr/C || NAME =~ *i_rx_data_iddr/D}]

if {[llength $rx_ports] > 0 && [llength $iddr_pins] > 0} {
  puts "INFO: Applying axi_ad9361_delay.tcl (rx ports + iddr pins found)"
  if {[catch {source "$ad_hdl_dir/library/axi_ad9361/axi_ad9361_delay.tcl"} err]} {
    puts "WARNING: axi_ad9361_delay.tcl failed; continuing anyway: $err"
  }
} else {
  puts "WARNING: Skipping axi_ad9361_delay.tcl (expected rx_*_in* ports / i_rx_data_iddr pins not found)"
}

