# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/RISCV/RISCV.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV || ORIG_REF_NAME==RISCV} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_proc_sys_reset_0_0/RISCV_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_proc_sys_reset_0_0 || ORIG_REF_NAME==RISCV_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_processing_system7_0_0/RISCV_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_processing_system7_0_0 || ORIG_REF_NAME==RISCV_processing_system7_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_util_vector_logic_0_0/RISCV_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_util_vector_logic_0_0 || ORIG_REF_NAME==RISCV_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_xlconstant_0_0/RISCV_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_xlconstant_0_0 || ORIG_REF_NAME==RISCV_xlconstant_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_xlconstant_1_0/RISCV_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_xlconstant_1_0 || ORIG_REF_NAME==RISCV_xlconstant_1_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_xlconstant_2_0/RISCV_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_xlconstant_2_0 || ORIG_REF_NAME==RISCV_xlconstant_2_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_pc_unit_0_0/RISCV_pc_unit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_pc_unit_0_0 || ORIG_REF_NAME==RISCV_pc_unit_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_xlconstant_0_1/RISCV_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_xlconstant_0_1 || ORIG_REF_NAME==RISCV_xlconstant_0_1} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_decoder_0_0/RISCV_rv32i_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_decoder_0_0 || ORIG_REF_NAME==RISCV_rv32i_decoder_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_regfile_0_0/RISCV_rv32i_regfile_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_regfile_0_0 || ORIG_REF_NAME==RISCV_rv32i_regfile_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_control_full_0_0/RISCV_rv32i_control_full_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_control_full_0_0 || ORIG_REF_NAME==RISCV_rv32i_control_full_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_ram_datav_0_0/RISCV_rv32i_ram_datav_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_ram_datav_0_0 || ORIG_REF_NAME==RISCV_rv32i_ram_datav_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_alu_0_0/RISCV_rv32i_alu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_alu_0_0 || ORIG_REF_NAME==RISCV_rv32i_alu_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_lsu_0_0/RISCV_rv32i_lsu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_lsu_0_0 || ORIG_REF_NAME==RISCV_rv32i_lsu_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_addr_imm_mux_0_0/RISCV_rv32i_addr_imm_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_addr_imm_mux_0_0 || ORIG_REF_NAME==RISCV_rv32i_addr_imm_mux_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_wb_mux_0_0/RISCV_rv32i_wb_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_wb_mux_0_0 || ORIG_REF_NAME==RISCV_rv32i_wb_mux_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_pc_redirect_0_0/RISCV_rv32i_pc_redirect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_pc_redirect_0_0 || ORIG_REF_NAME==RISCV_rv32i_pc_redirect_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_imm_mux_0_0/RISCV_rv32i_imm_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_imm_mux_0_0 || ORIG_REF_NAME==RISCV_rv32i_imm_mux_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_opA_mux_0_0/RISCV_rv32i_opA_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_opA_mux_0_0 || ORIG_REF_NAME==RISCV_rv32i_opA_mux_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_opB_mux_0_0/RISCV_rv32i_opB_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_opB_mux_0_0 || ORIG_REF_NAME==RISCV_rv32i_opB_mux_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_dist_mem_gen_0_0/RISCV_dist_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_dist_mem_gen_0_0 || ORIG_REF_NAME==RISCV_dist_mem_gen_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_pc_to_rom_addr_0_0/RISCV_pc_to_rom_addr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_pc_to_rom_addr_0_0 || ORIG_REF_NAME==RISCV_pc_to_rom_addr_0_0} -quiet] -quiet

# XDC: bd/RISCV/RISCV_ooc.xdc
