webtalk_init -webtalk_dir /media/steckler/xilinx_linux/SDR_custom/SDR/Software/CPU_N1_ONE_CYCLE_FULL/CPU_V1/CPU_V1.sim/sim_1/behav/xsim/xsim.dir/A_wrapper_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Dec 15 19:35:46 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ef97285f-b10c-47ec-b1dc-39577ac22529" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9575f41180e14107b52ae1c793f66669" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 4600H with Radeon Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1397.222 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "3.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5402992_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4160063506 -regid "" -xml /media/steckler/xilinx_linux/SDR_custom/SDR/Software/CPU_N1_ONE_CYCLE_FULL/CPU_V1/CPU_V1.sim/sim_1/behav/xsim/xsim.dir/A_wrapper_behav/webtalk/usage_statistics_ext_xsim.xml -html /media/steckler/xilinx_linux/SDR_custom/SDR/Software/CPU_N1_ONE_CYCLE_FULL/CPU_V1/CPU_V1.sim/sim_1/behav/xsim/xsim.dir/A_wrapper_behav/webtalk/usage_statistics_ext_xsim.html -wdm /media/steckler/xilinx_linux/SDR_custom/SDR/Software/CPU_N1_ONE_CYCLE_FULL/CPU_V1/CPU_V1.sim/sim_1/behav/xsim/xsim.dir/A_wrapper_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
