# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Sections/Sections.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections || ORIG_REF_NAME==Sections} -quiet] -quiet

# IP: bd/Sections/ip/Sections_gpio_mmio_0_0/Sections_gpio_mmio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_gpio_mmio_0_0 || ORIG_REF_NAME==Sections_gpio_mmio_0_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_ila_0_0/Sections_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_ila_0_0 || ORIG_REF_NAME==Sections_ila_0_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_mmio_decode_ram_gpio_0_0/Sections_mmio_decode_ram_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_mmio_decode_ram_gpio_0_0 || ORIG_REF_NAME==Sections_mmio_decode_ram_gpio_0_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_proc_sys_reset_0_0/Sections_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_proc_sys_reset_0_0 || ORIG_REF_NAME==Sections_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_rv32i_alu_0_0/Sections_rv32i_alu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_rv32i_alu_0_0 || ORIG_REF_NAME==Sections_rv32i_alu_0_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_rv32i_control_full_0_0/Sections_rv32i_control_full_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_rv32i_control_full_0_0 || ORIG_REF_NAME==Sections_rv32i_control_full_0_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_rv32i_decoder_0_0/Sections_rv32i_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_rv32i_decoder_0_0 || ORIG_REF_NAME==Sections_rv32i_decoder_0_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_rv32i_imm_mux_0_0/Sections_rv32i_imm_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_rv32i_imm_mux_0_0 || ORIG_REF_NAME==Sections_rv32i_imm_mux_0_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_rv32i_opA_mux_0_0/Sections_rv32i_opA_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_rv32i_opA_mux_0_0 || ORIG_REF_NAME==Sections_rv32i_opA_mux_0_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_rv32i_opB_mux_0_0/Sections_rv32i_opB_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_rv32i_opB_mux_0_0 || ORIG_REF_NAME==Sections_rv32i_opB_mux_0_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_rv32i_ram_datav_0_0/Sections_rv32i_ram_datav_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_rv32i_ram_datav_0_0 || ORIG_REF_NAME==Sections_rv32i_ram_datav_0_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_rv32i_regfile_0_0/Sections_rv32i_regfile_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_rv32i_regfile_0_0 || ORIG_REF_NAME==Sections_rv32i_regfile_0_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_rv32i_wb_mux_0_0/Sections_rv32i_wb_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_rv32i_wb_mux_0_0 || ORIG_REF_NAME==Sections_rv32i_wb_mux_0_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_xlconstant_0_0/Sections_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_xlconstant_0_0 || ORIG_REF_NAME==Sections_xlconstant_0_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_zynq_ultra_ps_e_1_0/Sections_zynq_ultra_ps_e_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_zynq_ultra_ps_e_1_0 || ORIG_REF_NAME==Sections_zynq_ultra_ps_e_1_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_dist_mem_gen_0_0/Sections_dist_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_dist_mem_gen_0_0 || ORIG_REF_NAME==Sections_dist_mem_gen_0_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_xlconstant_3_0/Sections_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_xlconstant_3_0 || ORIG_REF_NAME==Sections_xlconstant_3_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_pc_to_rom_addr_0_0/Sections_pc_to_rom_addr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_pc_to_rom_addr_0_0 || ORIG_REF_NAME==Sections_pc_to_rom_addr_0_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_pc_unit_0_0/Sections_pc_unit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_pc_unit_0_0 || ORIG_REF_NAME==Sections_pc_unit_0_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_rv32i_pc_redirect_0_0/Sections_rv32i_pc_redirect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_rv32i_pc_redirect_0_0 || ORIG_REF_NAME==Sections_rv32i_pc_redirect_0_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_xlconstant_1_0/Sections_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_xlconstant_1_0 || ORIG_REF_NAME==Sections_xlconstant_1_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_vio_0_0/Sections_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_vio_0_0 || ORIG_REF_NAME==Sections_vio_0_0} -quiet] -quiet

# IP: bd/Sections/ip/Sections_util_vector_logic_0_0/Sections_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_util_vector_logic_0_0 || ORIG_REF_NAME==Sections_util_vector_logic_0_0} -quiet] -quiet

# XDC: bd/Sections/ip/Sections_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Sections_ila_0_0 || ORIG_REF_NAME==Sections_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Sections/ip/Sections_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Sections_ila_0_0 || ORIG_REF_NAME==Sections_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Sections/ip/Sections_ila_0_0/Sections_ila_0_0_ooc.xdc

# XDC: bd/Sections/ip/Sections_proc_sys_reset_0_0/Sections_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Sections_proc_sys_reset_0_0 || ORIG_REF_NAME==Sections_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Sections/ip/Sections_proc_sys_reset_0_0/Sections_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Sections_proc_sys_reset_0_0 || ORIG_REF_NAME==Sections_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Sections/ip/Sections_zynq_ultra_ps_e_1_0/Sections_zynq_ultra_ps_e_1_0_ooc.xdc

# XDC: bd/Sections/ip/Sections_zynq_ultra_ps_e_1_0/Sections_zynq_ultra_ps_e_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Sections_zynq_ultra_ps_e_1_0 || ORIG_REF_NAME==Sections_zynq_ultra_ps_e_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Sections/ip/Sections_dist_mem_gen_0_0/Sections_dist_mem_gen_0_0_ooc.xdc

# XDC: bd/Sections/ip/Sections_vio_0_0/Sections_vio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sections_vio_0_0 || ORIG_REF_NAME==Sections_vio_0_0} -quiet] -quiet

# XDC: bd/Sections/ip/Sections_vio_0_0/Sections_vio_0_0_ooc.xdc

# XDC: bd/Sections/Sections_ooc.xdc
