# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/RISCV/RISCV.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV || ORIG_REF_NAME==RISCV} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_proc_sys_reset_0_0/RISCV_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_proc_sys_reset_0_0 || ORIG_REF_NAME==RISCV_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_xlconstant_0_0/RISCV_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_xlconstant_0_0 || ORIG_REF_NAME==RISCV_xlconstant_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_xlconstant_1_0/RISCV_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_xlconstant_1_0 || ORIG_REF_NAME==RISCV_xlconstant_1_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_xlconstant_2_0/RISCV_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_xlconstant_2_0 || ORIG_REF_NAME==RISCV_xlconstant_2_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_pc_unit_0_0/RISCV_pc_unit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_pc_unit_0_0 || ORIG_REF_NAME==RISCV_pc_unit_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_xlconstant_0_1/RISCV_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_xlconstant_0_1 || ORIG_REF_NAME==RISCV_xlconstant_0_1} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_decoder_0_0/RISCV_rv32i_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_decoder_0_0 || ORIG_REF_NAME==RISCV_rv32i_decoder_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_regfile_0_0/RISCV_rv32i_regfile_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_regfile_0_0 || ORIG_REF_NAME==RISCV_rv32i_regfile_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_control_full_0_0/RISCV_rv32i_control_full_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_control_full_0_0 || ORIG_REF_NAME==RISCV_rv32i_control_full_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_ram_datav_0_0/RISCV_rv32i_ram_datav_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_ram_datav_0_0 || ORIG_REF_NAME==RISCV_rv32i_ram_datav_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_alu_0_0/RISCV_rv32i_alu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_alu_0_0 || ORIG_REF_NAME==RISCV_rv32i_alu_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_wb_mux_0_0/RISCV_rv32i_wb_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_wb_mux_0_0 || ORIG_REF_NAME==RISCV_rv32i_wb_mux_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_pc_redirect_0_0/RISCV_rv32i_pc_redirect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_pc_redirect_0_0 || ORIG_REF_NAME==RISCV_rv32i_pc_redirect_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_imm_mux_0_0/RISCV_rv32i_imm_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_imm_mux_0_0 || ORIG_REF_NAME==RISCV_rv32i_imm_mux_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_opA_mux_0_0/RISCV_rv32i_opA_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_opA_mux_0_0 || ORIG_REF_NAME==RISCV_rv32i_opA_mux_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_rv32i_opB_mux_0_0/RISCV_rv32i_opB_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_rv32i_opB_mux_0_0 || ORIG_REF_NAME==RISCV_rv32i_opB_mux_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_dist_mem_gen_0_0/RISCV_dist_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_dist_mem_gen_0_0 || ORIG_REF_NAME==RISCV_dist_mem_gen_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_pc_to_rom_addr_0_0/RISCV_pc_to_rom_addr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_pc_to_rom_addr_0_0 || ORIG_REF_NAME==RISCV_pc_to_rom_addr_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_gpio_mmio_0_0/RISCV_gpio_mmio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_gpio_mmio_0_0 || ORIG_REF_NAME==RISCV_gpio_mmio_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_mmio_decode_ram_gpio_0_0/RISCV_mmio_decode_ram_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_mmio_decode_ram_gpio_0_0 || ORIG_REF_NAME==RISCV_mmio_decode_ram_gpio_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_zynq_ultra_ps_e_0_2/RISCV_zynq_ultra_ps_e_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_zynq_ultra_ps_e_0_2 || ORIG_REF_NAME==RISCV_zynq_ultra_ps_e_0_2} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_ila_0_0/RISCV_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_ila_0_0 || ORIG_REF_NAME==RISCV_ila_0_0} -quiet] -quiet

# IP: bd/RISCV/ip/RISCV_xlconstant_3_0/RISCV_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RISCV_xlconstant_3_0 || ORIG_REF_NAME==RISCV_xlconstant_3_0} -quiet] -quiet

# XDC: bd/RISCV/ip/RISCV_proc_sys_reset_0_0/RISCV_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==RISCV_proc_sys_reset_0_0 || ORIG_REF_NAME==RISCV_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/RISCV/ip/RISCV_proc_sys_reset_0_0/RISCV_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==RISCV_proc_sys_reset_0_0 || ORIG_REF_NAME==RISCV_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/RISCV/ip/RISCV_dist_mem_gen_0_0/RISCV_dist_mem_gen_0_0_ooc.xdc

# XDC: bd/RISCV/ip/RISCV_zynq_ultra_ps_e_0_2/RISCV_zynq_ultra_ps_e_0_2_ooc.xdc

# XDC: bd/RISCV/ip/RISCV_zynq_ultra_ps_e_0_2/RISCV_zynq_ultra_ps_e_0_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==RISCV_zynq_ultra_ps_e_0_2 || ORIG_REF_NAME==RISCV_zynq_ultra_ps_e_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/RISCV/ip/RISCV_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==RISCV_ila_0_0 || ORIG_REF_NAME==RISCV_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/RISCV/ip/RISCV_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==RISCV_ila_0_0 || ORIG_REF_NAME==RISCV_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/RISCV/ip/RISCV_ila_0_0/RISCV_ila_0_0_ooc.xdc

# XDC: bd/RISCV/RISCV_ooc.xdc
